name: Deploy Staging

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  deploy_staging:
    environment:
      name: staging
      url: https://staging.example.com
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Fake deploy step (örnek)
        run: |
          echo "kubectl apply -f k8s/      # gerçek komutlarını ekle"
          pip install -r requirements.txt
