name: Test and Analyze

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install test dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest coverage
      - name: Run tests & coverage
        run: |
          coverage run -m pytest
          coverage xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.qualitygate.wait=false
